version: '3.8'

services:
  # Existing TelemetryDatabase service
  telemetry-database:
    build: ./TelemetryDatabase
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - WEAVIATE_URL=http://weaviate:8080
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/telemetry
    depends_on:
      - redis
      - weaviate
      - postgres
    networks:
      - nexis-network
    volumes:
      - telemetry-logs:/app/logs
    restart: unless-stopped

  # NEW: LLM Service
  llm-service:
    build: ./llm-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - TELEMETRY_API_URL=http://telemetry-database:3000
      - TELEMETRY_WS_URL=ws://telemetry-database:3000
      - OLLAMA_HOST=http://localhost:11434
    depends_on:
      - telemetry-database
    networks:
      - nexis-network
    volumes:
      - llm-logs:/app/logs
      - ollama-models:/root/.ollama
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # Supporting services
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - nexis-network
    restart: unless-stopped

  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.23.7
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: 'text2vec-openai,text2vec-cohere,text2vec-huggingface,ref2vec-centroid,generative-openai,qna-openai'
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - weaviate-data:/var/lib/weaviate
    networks:
      - nexis-network
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: telemetry
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - nexis-network
    restart: unless-stopped

volumes:
  telemetry-logs:
  llm-logs:
  ollama-models:
  redis-data:
  weaviate-data:
  postgres-data:

networks:
  nexis-network:
    driver: bridge