name = "biometric-telemetry"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist/public"

[env.production]
name = "biometric-telemetry-prod"
# Will deploy to: biometric-telemetry.pages.dev

[env.preview]
name = "biometric-telemetry-preview"

# Environment variables for REAL CRYSTALS-Kyber and security
[env.production.vars]
NODE_ENV = "production"
REAL_CRYSTALS_KYBER_ENABLED = "true"
QUANTUM_RESISTANT_ENCRYPTION = "true"
# Security configuration
CORS_ALLOWED_ORIGINS = "https://biometric-telemetry.pages.dev,https://yourdomain.com"
WEBAUTHN_RP_ID = "biometric-telemetry.pages.dev"
WEBAUTHN_ORIGIN = "https://biometric-telemetry.pages.dev"
BCRYPT_ROUNDS = "14"
BIOMETRIC_SESSION_TIMEOUT = "1800"
BIOMETRIC_MAX_SESSIONS = "2"
BIOMETRIC_RETENTION_DAYS = "90"
LOG_LEVEL = "info"
ENABLE_STRUCTURED_LOGGING = "true"
FORCE_HTTPS = "true"
HSTS_MAX_AGE = "31536000"
ENABLE_COMPRESSION = "true"
CACHE_MAX_AGE = "3600"

[env.preview.vars]
NODE_ENV = "staging"
REAL_CRYSTALS_KYBER_ENABLED = "true"
QUANTUM_RESISTANT_ENCRYPTION = "true"
# Preview/staging security configuration
CORS_ALLOWED_ORIGINS = "https://biometric-telemetry-preview.pages.dev"
WEBAUTHN_RP_ID = "biometric-telemetry-preview.pages.dev"
WEBAUTHN_ORIGIN = "https://biometric-telemetry-preview.pages.dev"
BCRYPT_ROUNDS = "12"
BIOMETRIC_SESSION_TIMEOUT = "3600"
BIOMETRIC_MAX_SESSIONS = "3"
BIOMETRIC_RETENTION_DAYS = "30"
LOG_LEVEL = "debug"
ENABLE_STRUCTURED_LOGGING = "false"

# Secure secrets (set via Wrangler CLI)
# These will be encrypted by Cloudflare
# Use: wrangler secret put <SECRET_NAME> --env production
#      wrangler secret put <SECRET_NAME> --env preview
#
# Required secrets for PRODUCTION:
# - SESSION_SECRET (128-char high-entropy string)
# - WEAVIATE_URL (your production Weaviate cluster URL)
# - WEAVIATE_API_KEY (your production Weaviate API key)
# - PROMPT_USERNAME (production admin username)
# - PROMPT_PASSWORD (production admin password - use OAuth instead if possible)
# - ADMIN_OAUTH_CLIENT_ID (OAuth client ID for admin auth)
# - ADMIN_OAUTH_CLIENT_SECRET (OAuth client secret)
#
# Required secrets for PREVIEW:
# - SESSION_SECRET (128-char high-entropy string)
# - WEAVIATE_URL (your staging/preview Weaviate cluster URL)  
# - WEAVIATE_API_KEY (your staging/preview Weaviate API key)
# - PROMPT_USERNAME (staging admin username)
# - PROMPT_PASSWORD (staging admin password)

# D1 Database binding for biometric data storage
[[env.production.d1_databases]]
binding = "DB"
database_name = "biometric-telemetry-prod"
database_id = "" # Will be filled by Cloudflare CLI

[[env.preview.d1_databases]]
binding = "DB"
database_name = "biometric-telemetry-preview"
database_id = "" # Will be filled by Cloudflare CLI

# KV for session storage and caching
[[env.production.kv_namespaces]]
binding = "SESSIONS"
id = "" # Will be filled by Cloudflare CLI
preview_id = ""

[[env.preview.kv_namespaces]]
binding = "SESSIONS"
id = "" # Will be filled by Cloudflare CLI
preview_id = ""

# Analytics for monitoring CRYSTALS-Kyber usage
[env.production.analytics_engine_datasets]
binding = "SECURITY_ANALYTICS"

[env.preview.analytics_engine_datasets]
binding = "SECURITY_ANALYTICS"